version: '3.8'

services:
  # 1. The Backend Application (Node + Python)
  titan-api:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=titan-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Saurabh@845438
      - DB_NAME=titan_manufacturing
      - PYTHON_CMD=python3
      - OS_ENV=linux
    depends_on:
      - titan-db

  # 2. The Database
  titan-db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Saurabh@845438
      - MYSQL_DATABASE=titan_manufacturing
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: